import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useNavigate } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { Reveal } from "@/components/Reveal";
import { usePortfolioData } from "@/hooks/usePortfolioData";

const metric = (items, key) => items.find((item) => item.key === key)?.value;
const CHART_AXIS = "var(--chart-secondary)";
const CHART_GRID = "var(--chart-grid)";
const CHART_POSITIVE = "var(--positive)";
const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2, maximumFractionDigits: 2 });
const compactCurrency = (value) => value === 0 ? "₹0" : `₹${Math.abs(value) >= 100000 ? `${(value / 100000).toFixed(1)}L` : `${Math.round(value / 1000)}K`}`;

function FinancialTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null;
  return <div data-financial-tooltip className="rounded-md border border-white/15 bg-[#0A1E3F] px-3 py-2.5 text-sm shadow-lg"><div className="text-[11px] font-medium uppercase tracking-[.12em] text-[#CBD5E1]">{label}</div><div className="mt-1 font-medium text-white">{currency.format(payload[0].value)}</div></div>;
}

export default function Performance() {
  const navigate = useNavigate();
  const { data } = usePortfolioData();
  const { charts, headline, metrics, profile, charges } = data;
  const primaryKpis = [["Net P&L", headline.netPnl, "After charges"], ["Net ROI", headline.netRoi, `On ${profile.deployedCapital} deployed capital`], ["Win Rate", metric(metrics, "winrate"), "Profitable realised trades"], ["Realised Trades", metric(metrics, "active-trades"), "Through 10 Sep"]];
  const secondaryKpis = [["Gross P&L", headline.grossPnl], ["Gross ROI", headline.grossRoi], ["Total Charges", charges.totalFormatted], ["Avg Holding", metric(metrics, "holding")]];
  const contributors = charts.pnlAttribution.filter((item) => item.realizedPnl > 0).slice(0, 5);
  const maxContributor = Math.max(...contributors.map((item) => item.realizedPnl), 1);

  return <section id="performance" className="relative px-6 py-16 md:px-10 md:py-20"><div className="mx-auto max-w-7xl">
    <Reveal><div className="mb-4 flex items-center gap-3"><span className="text-[11px] uppercase tracking-[.28em] text-[#F5A623]">Performance</span><span className="h-px w-8 bg-[#F5A623]/50" /><span className="text-[11px] uppercase tracking-[.22em] text-[#94A3B8]">{profile.reportPeriod}</span></div><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><h2 className="max-w-2xl font-serif-display text-4xl leading-[1.05] tracking-tight text-white sm:text-5xl">Performance, measured with context.</h2><div className="max-w-xs text-sm leading-relaxed text-[#94A3B8] lg:text-right"><p>{profile.deployedCapital} average deployed capital</p><p>Realised equity transactions</p><p>{profile.reportPeriod}</p></div></div></Reveal>
    <Reveal delay={.05}><div data-financial-surface className="mt-10 grid border-y border-white/10 sm:grid-cols-2 lg:grid-cols-4">{primaryKpis.map(([label, value, detail], i) => <div key={label} data-financial-kpi="primary" data-testid={`snapshot-headline-${i}`} className={`px-5 py-6 md:px-6 md:py-7 ${i ? "border-t border-white/10 sm:border-l sm:border-t-0" : ""} ${i === 2 ? "lg:border-l" : ""}`}><div className="mb-3 h-px w-7 bg-[#F5A623]/65" /><div className="text-[10px] uppercase tracking-[.17em] text-[#64748B]">{label}</div><div className="mt-2 text-[clamp(1.9rem,3.2vw,2.75rem)] font-medium leading-none tracking-tight text-white tabular-nums">{value}</div><p className="mt-2 text-xs leading-relaxed text-[#94A3B8]">{detail}</p></div>)}</div></Reveal>
    <Reveal delay={.08}><div className="grid border-b border-white/10 sm:grid-cols-2 lg:grid-cols-4">{secondaryKpis.map(([label, value], i) => <div key={label} data-financial-kpi="secondary" className={`px-5 py-4 md:px-6 ${i ? "border-t border-white/10 sm:border-l sm:border-t-0" : ""} ${i === 2 ? "lg:border-l" : ""}`}><div className="text-[10px] uppercase tracking-[.16em] text-[#64748B]">{label}</div><div className="mt-1.5 text-xl font-medium leading-none text-white tabular-nums sm:text-2xl">{value}</div></div>)}</div></Reveal>
    <Reveal delay={.12}><div className="mt-10 grid gap-10 lg:grid-cols-[1.75fr_1fr] lg:gap-14"><div data-financial-surface className="min-w-0 border-t border-white/10 pt-5"><div className="mb-5 flex items-end justify-between gap-4"><div><div className="mb-3 h-px w-9 bg-[#F5A623]/65" /><h3 className="text-base font-medium text-white md:text-lg">Monthly realised P&amp;L</h3><p className="mt-1 text-[12px] text-[#94A3B8]">Discrete monthly outcome · September through 10 Sep</p></div><span className="text-[10px] uppercase tracking-[.15em] text-[#94A3B8]">₹ realised P&amp;L</span></div><div className="h-[230px] md:h-[260px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={charts.monthlyRealizedPnl} margin={{ top: 10, right: 6, left: 0, bottom: 0 }} barCategoryGap="28%"><CartesianGrid vertical={false} stroke={CHART_GRID} strokeDasharray="2 5" /><XAxis dataKey="month" stroke={CHART_AXIS} fontSize={11} tickLine={false} axisLine={false} dy={8} /><YAxis width={52} stroke={CHART_AXIS} fontSize={10} tickLine={false} axisLine={false} tickFormatter={compactCurrency} /><Tooltip cursor={{ fill: "rgba(212,175,55,.05)" }} content={<FinancialTooltip />} /><Bar dataKey="realizedPnl" barSize={22} radius={[2, 2, 0, 0]}>{charts.monthlyRealizedPnl.map((entry, index) => <Cell key={`${entry.month}-${index}`} fill={CHART_POSITIVE} fillOpacity={index === charts.monthlyRealizedPnl.length - 1 ? .68 : .9} />)}</Bar></BarChart></ResponsiveContainer></div></div><div data-financial-surface className="border-t border-white/10 pt-5"><div className="mb-6"><div className="mb-3 h-px w-9 bg-[#F5A623]/65" /><h3 className="text-base font-medium text-white md:text-lg">Top contributors</h3><p className="mt-1 text-[12px] text-[#94A3B8]">Stocks contributing most to realised P&amp;L</p></div><div className="space-y-5">{contributors.map((item) => <div key={item.stock}><div className="mb-2 flex items-center justify-between gap-3 text-xs"><span className="truncate text-[#CBD5E1]">{item.stock}</span><span className="shrink-0 tabular-nums text-[#94A3B8]">{currency.format(item.realizedPnl)}</span></div><div className="h-1 overflow-hidden bg-white/[.08]"><div className="h-full bg-[#D4AF37]" style={{ width: `${(item.realizedPnl / maxContributor) * 100}%` }} /></div></div>)}</div></div></div></Reveal>
    <Reveal delay={.16}><div className="mt-8 flex flex-col gap-3 border-t border-white/10 pt-5 text-sm leading-relaxed text-[#94A3B8] sm:flex-row sm:items-center sm:justify-between"><p>85.14% win rate across 426 realised trades, with an average holding period of 68 days.</p><button onClick={() => navigate("/portfolio")} className="group inline-flex shrink-0 items-center gap-2 text-[#E7C56B] transition-colors hover:text-[#F5A623]">View detailed performance <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></button></div><p className="mt-5 text-[11px] text-[#71839A]">Source: Upstox Realised P&amp;L Report · {profile.reportPeriod}. September reflects realised transactions through 10 Sep 2026.</p></Reveal>
  </div></section>;
}
