import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

const API = `${process.env.REACT_APP_BACKEND_URL || ""}/api`;
const filters = [["ALL", "All"], ["ARTICLE", "Articles"], ["PDF", "Reports"], ["SPREADSHEET", "Spreadsheets"], ["IMAGE", "Visuals"]];
const labels = { ARTICLE: "Article", PDF: "Report", SPREADSHEET: "Spreadsheet", IMAGE: "Visual", FILE: "Resource" };

export default function BlogPage() {
  const [filter, setFilter] = useState("ALL"); const [items, setItems] = useState([]); const [error, setError] = useState(false);
  useEffect(() => { let live = true; fetch(`${API}/content${filter === "ALL" ? "" : `?content_type=${filter}`}`).then((r) => r.ok ? r.json() : Promise.reject()).then((data) => live && setItems(data)).catch(() => live && setError(true)); return () => { live = false; }; }, [filter]);
  return <main className="pt-24 md:pt-28"><section className="px-6 md:px-10 pt-16 pb-12 border-b border-white/10"><div className="max-w-7xl mx-auto"><div className="uppercase tracking-[.3em] text-[11px] text-[#F5A623]">Blog / Research</div><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-5 mt-4"><h1 className="font-serif-display text-5xl md:text-6xl text-white">Ideas, research and resources.</h1><Link to="/blog/admin/login" className="text-xs text-[#71839A] hover:text-[#F5A623]">Admin Login</Link></div><p className="mt-5 max-w-xl text-[#94A3B8]">Published notes, reports and resources from Nishant Jain.</p></div></section><section className="px-6 md:px-10 py-10"><div className="max-w-7xl mx-auto"><div className="flex gap-2 overflow-x-auto pb-2">{filters.map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`px-4 py-2 rounded-full text-sm whitespace-nowrap border ${filter === value ? "bg-[#F5A623] text-[#050E1D] border-[#F5A623]" : "border-white/15 text-[#94A3B8] hover:text-white"}`}>{label}</button>)}</div>{error ? <p className="mt-12 text-[#C98182]">Research content is temporarily unavailable.</p> : <div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{items.map((item) => <Link key={item.id} to={`/blog/${item.slug}`} className="group rounded-xl overflow-hidden border border-white/10 bg-[#0A1E3F]/35 hover:border-[#F5A623]/50 transition-colors"><div className="h-36 bg-gradient-to-br from-[#12315f] to-[#081426] flex items-end p-5">{item.coverImageUrl ? <img src={item.coverImageUrl} alt="" className="absolute inset-0 w-full h-full object-cover" /> : <span className="relative text-[11px] uppercase tracking-[.18em] text-[#E7C56B]">{labels[item.contentType]}</span>}</div><div className="p-5"><div className="text-[10px] uppercase tracking-[.16em] text-[#E7C56B]">{labels[item.contentType]} · {item.publishedAt?.slice(0, 10)}</div><h2 className="mt-3 font-serif-display text-3xl text-white group-hover:text-[#F5A623]">{item.title}</h2><p className="mt-3 text-sm leading-relaxed text-[#94A3B8]">{item.excerpt}</p><span className="mt-5 inline-block text-sm text-white">Open →</span></div></Link>)}</div>}{!error && !items.length && <p className="mt-12 text-[#94A3B8]">No published content in this category yet.</p>}</div></section></main>;
}
