import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ExternalLink } from "lucide-react";
import { usePortfolioData } from "@/hooks/usePortfolioData";
import { useTheme } from "@/components/ThemeProvider";

const PNL_REPORT_URL = `${process.env.PUBLIC_URL || ""}/reports/realizedPnL_EQ_2026-04-01_To_2026-08-31_BR2287.pdf`;
const CHART_PRIMARY = "var(--chart-primary)";
const CHART_POSITIVE = "var(--positive)";
const CHART_NEGATIVE = "var(--negative)";
const CHART_AXIS = "var(--chart-secondary)";
const CHART_GRID = "var(--chart-grid)";
const CHART_HIGHLIGHT = "var(--chart-highlight)";
const INDIAN_CURRENCY = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2 });
const compactCurrency = (value) => `₹${Math.abs(value) >= 100000 ? `${(value / 100000).toFixed(1)}L` : Math.round(value).toLocaleString("en-IN")}`;
const metric = (items, key) => items.find((item) => item.key === key)?.value;

function SectionHeading({ eyebrow, title, children }) { return <div className="mb-7 flex flex-col gap-4 sm:mb-9 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 text-[11px] uppercase tracking-[.22em] text-[#F5A623] sm:tracking-[.28em]">{eyebrow}</div><h2 className="font-serif-display text-3xl leading-tight text-white sm:text-5xl">{title}</h2></div>{children && <div className="max-w-md text-sm leading-relaxed text-[#94A3B8]">{children}</div>}</div>; }
function FinancialTooltip({ active, payload, label, unit = "" }) { return active && payload?.length ? <div data-financial-tooltip className="rounded-lg border border-white/10 bg-[#07182F] px-4 py-3 text-sm shadow-xl"><div className="text-[11px] font-medium uppercase tracking-[.14em] text-[#94A3B8]">{label}</div><div className="mt-1.5 font-medium text-white">{unit === "trades" ? `${payload[0].value} trades` : INDIAN_CURRENCY.format(payload[0].value)}</div></div> : null; }

function FinancialArea({ data, dataKey, xKey, label, gradientId }) {
  return <AreaChart data={data} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={CHART_PRIMARY} stopOpacity={.16} /><stop offset="100%" stopColor={CHART_PRIMARY} stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke={CHART_GRID} strokeDasharray="2 5" /><XAxis dataKey={xKey} stroke={CHART_AXIS} fontSize={11} tickLine={false} axisLine={false} dy={8} /><YAxis width={58} stroke={CHART_AXIS} fontSize={11} tickLine={false} axisLine={false} tickFormatter={compactCurrency} /><Tooltip cursor={{ stroke: CHART_HIGHLIGHT, strokeWidth: 1 }} content={<FinancialTooltip />} /><Area type="monotone" name={label} dataKey={dataKey} stroke={CHART_PRIMARY} strokeWidth={2.25} fill={`url(#${gradientId})`} activeDot={{ r: 4.5, fill: CHART_HIGHLIGHT, stroke: "#FFFFFF", strokeWidth: 2 }} /></AreaChart>;
}

export default function PortfolioPage() {
  const { isLight } = useTheme();
  const { data } = usePortfolioData();
  const { charts, charges, headline, metrics, profile, summary } = data;
  const primaryOverview = [["Gross P&L Generated", headline.grossPnl], ["Net P&L After Charges", headline.netPnl]];
  const secondaryOverview = [["Gross ROI", headline.grossRoi], ["Net ROI", headline.netRoi]];
  const support = [["Win Rate", metric(metrics, "winrate")], ["Realised Trades", metric(metrics, "active-trades")], ["Avg Holding Period", metric(metrics, "holding")], ["Profitable", summary.winningTrades], ["Loss-making", summary.losingTrades], ["Zero P&L", summary.zeroPnlTrades]];
  const chargeRows = [["SEBI fees", charges.breakdown.sebiFees], ["Turnover charges", charges.breakdown.turnoverCharges], ["Brokerage", charges.breakdown.brokerage], ["Demat transaction charges", charges.breakdown.dematTransactionCharges], ["Integrated GST", charges.breakdown.integratedGst], ["Securities transaction tax", charges.breakdown.securitiesTransactionTax], ["Stamp duty", charges.breakdown.stampDuty]];

  return <main className="pt-20 md:pt-28"><header className="border-b border-white/10 bg-[radial-gradient(circle_at_85%_0%,rgba(245,166,35,.12),transparent_28%)] px-4 pb-10 pt-14 sm:px-6 md:px-10 md:pt-20"><div className="mx-auto max-w-7xl"><div className="mb-4 text-[11px] uppercase tracking-[.22em] text-[#F5A623] sm:tracking-[.3em]">Portfolio Report</div><h1 className="max-w-4xl font-serif-display text-[2.85rem] leading-[.98] text-white sm:text-6xl lg:text-7xl">Realised performance, <span className="italic text-[#E7C56B]">clearly sourced.</span></h1><div className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-sm text-[#CBD5E1] sm:gap-x-6"><span>{profile.reportPeriod}</span><span className="text-[#F5A623]/60">•</span><span>Reference capital: {profile.deployedCapital}</span></div><p className="mt-5 max-w-2xl leading-relaxed text-[#94A3B8]">Every metric and chart below is derived from the active Upstox realised P&amp;L ledger.</p></div></header>
    <section className="px-4 py-12 sm:px-6 md:px-10 md:py-16"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Executive Summary" title="The essentials, clearly weighted." /><div data-financial-surface className="overflow-hidden rounded-xl border border-white/10 bg-[#0A1E3F]/35"><div className="grid sm:grid-cols-2">{primaryOverview.map(([label, value], i) => <div key={label} data-financial-kpi="primary" className={`px-5 py-7 md:px-7 md:py-8 ${i ? "border-t border-white/10 sm:border-l sm:border-t-0" : ""}`}><div className="mb-3 h-px w-7 bg-[#F5A623]/65" /><div className="text-[10px] uppercase tracking-[.16em] text-[#94A3B8]">{label}</div><div className="mt-3 text-[1.9rem] font-semibold leading-none text-white tabular-nums sm:text-[2.55rem]">{value}</div></div>)}</div><div className="grid border-t border-white/10 sm:grid-cols-2">{secondaryOverview.map(([label, value], i) => <div key={label} data-financial-kpi="secondary" className={`px-5 py-5 md:px-7 ${i ? "border-t border-white/10 sm:border-l sm:border-t-0" : ""}`}><div className="text-[10px] uppercase tracking-[.16em] text-[#71839A]">{label}</div><div className="mt-2 text-xl font-medium leading-none text-white tabular-nums sm:text-2xl">{value}</div></div>)}</div></div><div data-financial-surface className="mt-5 grid grid-cols-2 rounded-xl border border-white/10 p-3 sm:grid-cols-3 lg:grid-cols-6">{support.map(([label, value], i) => <div key={label} className={`min-w-0 px-2 py-2 sm:px-4 ${i ? "border-l border-white/10" : ""}`}><div className="text-[10px] uppercase tracking-[.13em] text-[#71839A]">{label}</div><div className="mt-2 text-base text-white tabular-nums sm:text-lg">{value}</div></div>)}</div><div className="mt-6 flex justify-stretch sm:justify-end"><a href={PNL_REPORT_URL} target="_blank" rel="noopener noreferrer" data-testid="view-full-pnl-report" className="group inline-flex w-full items-center justify-center gap-2.5 rounded-full bg-[#F5A623] px-6 py-3 text-sm font-medium text-[#050E1D] transition-colors hover:bg-[#E19212] sm:w-auto">View Full P&amp;L Report <ExternalLink size={16} /></a></div></div></section>
    <section className="border-y border-white/10 bg-[#07182F]/60 px-4 py-12 sm:px-6 md:px-10 md:py-16"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Realised P&L" title="How gains accumulated.">Calendar-month and cumulative realised P&amp;L from the {summary.tradeCount} ledger rows.</SectionHeading><div className="grid gap-5 lg:grid-cols-2 lg:gap-6"><ChartCard title="Monthly realised P&L"><ResponsiveContainer width="100%" height="100%">{isLight ? <FinancialArea data={charts.monthlyRealizedPnl} dataKey="realizedPnl" xKey="month" label="Monthly realised P&L" gradientId="portfolio-monthly-fill" /> : <BarChart data={charts.monthlyRealizedPnl}><XAxis dataKey="month" stroke={CHART_AXIS} fontSize={11} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip content={<FinancialTooltip />} /><Bar dataKey="realizedPnl" radius={[4,4,0,0]}>{charts.monthlyRealizedPnl.map((row) => <Cell key={row.month} fill={row.realizedPnl >= 0 ? CHART_POSITIVE : CHART_NEGATIVE} />)}</Bar></BarChart>}</ResponsiveContainer></ChartCard><ChartCard title="Cumulative realised P&L"><ResponsiveContainer width="100%" height="100%">{isLight ? <FinancialArea data={charts.cumulativeRealizedPnl} dataKey="realizedPnl" xKey="date" label="Cumulative realised P&L" gradientId="portfolio-cumulative-fill" /> : <BarChart data={charts.cumulativeRealizedPnl}><XAxis dataKey="date" hide /><YAxis hide /><Tooltip content={<FinancialTooltip />} /><Bar dataKey="realizedPnl" fill={CHART_PRIMARY} radius={[3,3,0,0]} /></BarChart>}</ResponsiveContainer></ChartCard></div></div></section>
    <section className="px-4 py-12 sm:px-6 md:px-10 md:py-16"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="P&L Attribution" title="Where returns came from.">Realised P&amp;L by symbol from the {profile.reportPeriod} ledger.</SectionHeading><ChartCard title="Stock contribution"><ResponsiveContainer width="100%" height="100%"><BarChart data={charts.pnlAttribution} layout="vertical" margin={{ left: 4, right: 12 }}><CartesianGrid horizontal={false} stroke={CHART_GRID} strokeDasharray="2 5" /><XAxis type="number" hide /><YAxis type="category" dataKey="stock" width={96} tick={{ fill: CHART_AXIS, fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip content={<FinancialTooltip />} /><Bar dataKey="realizedPnl" radius={3} barSize={16}>{charts.pnlAttribution.map((row) => <Cell key={row.stock} fill={row.realizedPnl >= 0 ? CHART_POSITIVE : CHART_NEGATIVE} />)}</Bar></BarChart></ResponsiveContainer></ChartCard></div></section>
    <section className="border-y border-white/10 bg-[#07182F]/60 px-4 py-12 sm:px-6 md:px-10 md:py-16"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Trade Analysis" title="Outcomes and holding periods." /><div className="grid gap-5 lg:grid-cols-2 lg:gap-6"><ChartCard title="Trade outcomes"><ResponsiveContainer width="100%" height="100%"><BarChart data={charts.outcomes}><CartesianGrid vertical={false} stroke={CHART_GRID} strokeDasharray="2 5" /><XAxis dataKey="outcome" stroke={CHART_AXIS} fontSize={10} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip content={<FinancialTooltip unit="trades" />} /><Bar dataKey="trades" radius={[4,4,0,0]} barSize={18}>{charts.outcomes.map((row) => <Cell key={row.outcome} fill={row.outcome === "Profitable" ? CHART_POSITIVE : row.outcome === "Loss-making" ? CHART_NEGATIVE : CHART_AXIS} />)}</Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Holding period distribution"><ResponsiveContainer width="100%" height="100%"><BarChart data={charts.holdingPeriodDistribution}><CartesianGrid vertical={false} stroke={CHART_GRID} strokeDasharray="2 5" /><XAxis dataKey="bucket" stroke={CHART_AXIS} fontSize={10} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip content={<FinancialTooltip unit="trades" />} /><Bar dataKey="trades" fill={CHART_PRIMARY} radius={[4,4,0,0]} barSize={18} /></BarChart></ResponsiveContainer></ChartCard></div></div></section>
    <section className="px-4 py-12 sm:px-6 md:px-10 md:py-16"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Charges" title="Costs, reconciled.">Gross P&amp;L less total charges equals net P&amp;L exactly.</SectionHeading><div className="grid gap-5 lg:grid-cols-[1fr_.8fr] lg:gap-6"><div data-financial-surface className="overflow-hidden rounded-xl border border-white/10 bg-[#0A1E3F]/35">{chargeRows.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-4 border-b border-white/10 px-4 py-4 text-sm last:border-0 sm:px-6"><span className="min-w-0 text-[#CBD5E1]">{label}</span><span className="shrink-0 text-right font-medium text-white tabular-nums">{INDIAN_CURRENCY.format(value)}</span></div>)}</div><div data-financial-surface className="rounded-xl border border-[#F5A623]/30 bg-[#F5A623]/5 p-5 sm:p-6"><div className="text-[10px] uppercase tracking-[.16em] text-[#E7C56B]">Reconciliation</div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4 text-[#CBD5E1]"><span>Gross P&amp;L</span><b className="text-right text-white">{headline.grossPnl}</b></div><div className="flex justify-between gap-4 text-[#CBD5E1]"><span>Total charges</span><b className="text-right text-white">− {charges.totalFormatted}</b></div><div className="flex justify-between gap-4 border-t border-[#F5A623]/25 pt-3 text-[#CBD5E1]"><span>Net P&amp;L</span><b className="text-right text-[#E7C56B]">{headline.netPnl}</b></div></div></div></div></div></section>
  </main>;
}

function ChartCard({ title, children }) { return <div data-financial-surface className="min-w-0 rounded-xl border border-white/10 bg-[#081B35] p-5 md:p-7"><div className="mb-5"><div className="mb-3 h-px w-7 bg-[#F5A623]/55" /><h3 className="text-sm font-medium text-white sm:text-base">{title}</h3></div><div className="h-[270px] min-w-0 sm:h-[330px]">{children}</div></div>; }
