import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ExternalLink } from "lucide-react";
import { usePortfolioData } from "@/hooks/usePortfolioData";

const PNL_REPORT_URL = "/reports/realizedPnL_EQ_2026-04-01_To_2026-08-23_BR2287.pdf";
const GOLD = "#F5A623";
const INDIAN_CURRENCY = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2 });
const metric = (items, key) => items.find((item) => item.key === key)?.value;

function SectionHeading({ eyebrow, title, children }) { return <div className="mb-9 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 text-[11px] uppercase tracking-[.28em] text-[#F5A623]">{eyebrow}</div><h2 className="font-serif-display text-4xl leading-none text-white sm:text-5xl">{title}</h2></div>{children && <div className="max-w-md text-sm leading-relaxed text-[#94A3B8]">{children}</div>}</div>; }
function CurrencyTooltip({ active, payload, label }) { return active && payload?.length ? <div className="rounded-lg border border-white/10 bg-[#07182F] px-3 py-2.5 text-sm shadow-xl"><div className="mb-1 text-[#94A3B8]">{label}</div><div className="text-white">{INDIAN_CURRENCY.format(payload[0].value)}</div></div> : null; }
function CountTooltip({ active, payload, label }) { return active && payload?.length ? <div className="rounded-lg border border-white/10 bg-[#07182F] px-3 py-2.5 text-sm shadow-xl"><div className="mb-1 text-[#94A3B8]">{label}</div><div className="text-white">{payload[0].value} trades</div></div> : null; }

export default function PortfolioPage() {
  const { data } = usePortfolioData();
  const { charts, charges, headline, metrics, profile, summary } = data;
  const overview = [["Gross P&L Generated", headline.grossPnl], ["Net P&L After Charges", headline.netPnl], ["Gross ROI", headline.grossRoi], ["Net ROI", headline.netRoi]];
  const support = [["Win Rate", metric(metrics, "winrate")], ["Realised Trades", metric(metrics, "active-trades")], ["Avg Holding Period", metric(metrics, "holding")], ["Profitable", summary.winningTrades], ["Loss-making", summary.losingTrades], ["Zero P&L", summary.zeroPnlTrades]];
  const chargeRows = [["SEBI fees", charges.breakdown.sebiFees], ["Turnover charges", charges.breakdown.turnoverCharges], ["Brokerage", charges.breakdown.brokerage], ["Demat transaction charges", charges.breakdown.dematTransactionCharges], ["Integrated GST", charges.breakdown.integratedGst], ["Securities transaction tax", charges.breakdown.securitiesTransactionTax], ["Stamp duty", charges.breakdown.stampDuty]];

  return <main className="pt-24 md:pt-28"><header className="border-b border-white/10 bg-[radial-gradient(circle_at_85%_0%,rgba(245,166,35,.12),transparent_28%)] px-6 pb-12 pt-16 md:px-10 md:pt-20"><div className="mx-auto max-w-7xl"><div className="mb-5 text-[11px] uppercase tracking-[.3em] text-[#F5A623]">Portfolio Report</div><h1 className="max-w-4xl font-serif-display text-5xl leading-[.95] text-white sm:text-6xl lg:text-7xl">Realised performance, <span className="italic text-[#E7C56B]">clearly sourced.</span></h1><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[#CBD5E1]"><span>{profile.reportPeriod}</span><span className="text-[#F5A623]/60">•</span><span>Reference capital: {profile.deployedCapital}</span></div><p className="mt-5 max-w-2xl leading-relaxed text-[#94A3B8]">Every metric and chart below is derived from the active Upstox realised P&amp;L ledger.</p></div></header>
    <section className="px-6 py-16 md:px-10"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Executive Summary" title="The essentials, clearly weighted." /><div className="grid overflow-hidden rounded-xl border border-white/10 bg-[#0A1E3F]/35 sm:grid-cols-2 lg:grid-cols-4">{overview.map(([label, value], i) => <div key={label} className={`border-white/10 p-5 md:p-6 ${i ? "lg:border-l" : ""} ${i < 2 ? "sm:border-b lg:border-b-0" : ""}`}><div className="min-h-8 text-[10px] uppercase tracking-[.16em] text-[#94A3B8]">{label}</div><div className="mt-3 text-2xl font-semibold text-white tabular-nums">{value}</div></div>)}</div><div className="mt-5 grid grid-cols-2 overflow-hidden rounded-xl border border-white/10 bg-white/10 md:grid-cols-3 lg:grid-cols-6">{support.map(([label, value]) => <div key={label} className="bg-[#07182F] p-4"><div className="text-[10px] uppercase tracking-[.13em] text-[#71839A]">{label}</div><div className="mt-2 text-lg text-white tabular-nums">{value}</div></div>)}</div><div className="mt-6 flex justify-end"><a href={PNL_REPORT_URL} target="_blank" rel="noopener noreferrer" data-testid="view-full-pnl-report" className="group inline-flex items-center gap-2.5 rounded-full bg-[#F5A623] px-6 py-3 text-sm font-medium text-[#050E1D] transition-colors hover:bg-[#E19212]">View Full P&amp;L Report <ExternalLink size={16} /></a></div></div></section>
    <section className="border-y border-white/10 bg-[#07182F]/60 px-6 py-16 md:px-10"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Realised P&L" title="How gains accumulated.">Calendar-month and cumulative realised P&amp;L from the 375 ledger rows.</SectionHeading><div className="grid gap-6 lg:grid-cols-2"><ChartCard title="Monthly realised P&L"><BarChart data={charts.monthlyRealizedPnl}><XAxis dataKey="month" stroke="#94A3B8" fontSize={11} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip content={<CurrencyTooltip />} /><Bar dataKey="realizedPnl" radius={[4,4,0,0]}>{charts.monthlyRealizedPnl.map((row) => <Cell key={row.month} fill={row.realizedPnl >= 0 ? GOLD : "#A66267"} />)}</Bar></BarChart></ChartCard><ChartCard title="Cumulative realised P&L"><BarChart data={charts.cumulativeRealizedPnl}><XAxis dataKey="date" hide /><YAxis hide /><Tooltip content={<CurrencyTooltip />} /><Bar dataKey="realizedPnl" fill={GOLD} radius={[3,3,0,0]} /></BarChart></ChartCard></div></div></section>
    <section className="px-6 py-16 md:px-10"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="P&L Attribution" title="Where returns came from.">Realised P&amp;L by symbol from the {profile.reportPeriod} ledger.</SectionHeading><ChartCard title="Stock contribution"><BarChart data={charts.pnlAttribution} layout="vertical" margin={{ left: 24, right: 15 }}><XAxis type="number" hide /><YAxis type="category" dataKey="stock" width={125} tick={{ fill: "#CBD5E1", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip content={<CurrencyTooltip />} /><Bar dataKey="realizedPnl" radius={3}>{charts.pnlAttribution.map((row) => <Cell key={row.stock} fill={row.realizedPnl >= 0 ? GOLD : "#A66267"} />)}</Bar></BarChart></ChartCard></div></section>
    <section className="border-y border-white/10 bg-[#07182F]/60 px-6 py-16 md:px-10"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Trade Analysis" title="Outcomes and holding periods." /><div className="grid gap-6 lg:grid-cols-2"><ChartCard title="Trade outcomes"><BarChart data={charts.outcomes}><XAxis dataKey="outcome" stroke="#94A3B8" fontSize={11} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip content={<CountTooltip />} /><Bar dataKey="trades" radius={[4,4,0,0]}>{charts.outcomes.map((row) => <Cell key={row.outcome} fill={row.outcome === "Profitable" ? "#34D399" : row.outcome === "Loss-making" ? "#A66267" : "#94A3B8"} />)}</Bar></BarChart></ChartCard><ChartCard title="Holding period distribution"><BarChart data={charts.holdingPeriodDistribution}><XAxis dataKey="bucket" stroke="#94A3B8" fontSize={11} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip content={<CountTooltip />} /><Bar dataKey="trades" fill={GOLD} radius={[4,4,0,0]} /></BarChart></ChartCard></div></div></section>
    <section className="px-6 py-16 md:px-10"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Charges" title="Costs, reconciled.">Gross P&amp;L less total charges equals net P&amp;L exactly.</SectionHeading><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><div className="overflow-hidden rounded-xl border border-white/10 bg-[#0A1E3F]/35">{chargeRows.map(([label, value]) => <div key={label} className="flex justify-between border-b border-white/10 px-6 py-4 text-sm last:border-0"><span className="text-[#CBD5E1]">{label}</span><span className="font-medium text-white tabular-nums">{INDIAN_CURRENCY.format(value)}</span></div>)}</div><div className="rounded-xl border border-[#F5A623]/30 bg-[#F5A623]/5 p-6"><div className="text-[10px] uppercase tracking-[.16em] text-[#E7C56B]">Reconciliation</div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between text-[#CBD5E1]"><span>Gross P&amp;L</span><b className="text-white">{headline.grossPnl}</b></div><div className="flex justify-between text-[#CBD5E1]"><span>Total charges</span><b className="text-white">− {charges.totalFormatted}</b></div><div className="flex justify-between border-t border-[#F5A623]/25 pt-3 text-[#CBD5E1]"><span>Net P&amp;L</span><b className="text-[#E7C56B]">{headline.netPnl}</b></div></div></div></div></div></section>
  </main>;
}

function ChartCard({ title, children }) { return <div className="rounded-xl border border-white/10 bg-[#081B35] p-4 md:p-6"><h3 className="mb-5 text-base font-medium text-white">{title}</h3><div className="h-[330px]"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></div>; }
